/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1_hectorreyes;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Onasis Reyes
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);

        //Agregar Persona
        jT_ocupacion.setEnabled(false);
        jT_horario.setEnabled(false);
        jT_tiempo.setEnabled(false);
        jT_sueldo.setEnabled(false);
        jT_usuario.setEnabled(!true);
        jT_contraseña.setEnabled(!true);
        jR_sucursal.setEnabled(!true);
        jR_gerente.setEnabled(!true);//*/

        //Agregar Artículo
        jT_nVol.setEnabled(false);
        jC_estadoComic.setEnabled(false);
        jT_descripcionComic.setEnabled(false);

        jT_casaElab.setEnabled(false);
        jT_edicion.setEnabled(false);
        jT_paisElab.setEnabled(false);

        jT_descripcionFigura.setEnabled(false);
        jT_instruccionesArm.setEnabled(false);
        jT_garantía.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator7 = new javax.swing.JSeparator();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTbl_principal = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jT_identificacion1 = new javax.swing.JTextField();
        jT_nombre1 = new javax.swing.JTextField();
        jT_edad1 = new javax.swing.JTextField();
        jT_altura1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jT_peso1 = new javax.swing.JTextField();
        jC_sexo1 = new javax.swing.JComboBox<>();
        jC_estadoC1 = new javax.swing.JComboBox<>();
        jC_TipoPersona = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jT_usuario = new javax.swing.JTextField();
        jR_gerente = new javax.swing.JRadioButton();
        jR_sucursal = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jT_sueldo = new javax.swing.JTextField();
        jT_ocupacion = new javax.swing.JTextField();
        jT_horario = new javax.swing.JTextField();
        jT_tiempo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btn_GuardarPersonas = new javax.swing.JButton();
        jT_contraseña = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jC_ingresadoPor = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        btn_colorArt = new javax.swing.JButton();
        jT_titulo = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_descripcionArt = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jT_editorial = new javax.swing.JTextField();
        rbtn_Comic = new javax.swing.JRadioButton();
        rbtn_Figura = new javax.swing.JRadioButton();
        rbtn_Juego = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jT_nVol = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_descripcionComic = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jC_estadoComic = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jT_edicion = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jT_casaElab = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jT_paisElab = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jT_descripcionFigura = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jT_instruccionesArm = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jT_garantía = new javax.swing.JTextField();
        btn_guardarArt = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jT_Tam = new javax.swing.JTextField();
        jT_puntuacion = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jC_emisor = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jC_receptor = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jT_enviarMensaje = new javax.swing.JTextArea();
        btn_enviar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102)));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel9.setText("Identificación");

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel15.setText("Altura");

        jC_sexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Hombre", "Mujer" }));

        jC_estadoC1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Casad@", "Solter@" }));

        jC_TipoPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Gerente", "Personal General" }));
        jC_TipoPersona.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jC_TipoPersonaItemStateChanged(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel16.setText("Tipo de Persona");

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel10.setText("Sexo");

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel11.setText("Nombre");

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel12.setText("Edad");

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel13.setText("Estado Civil");

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel14.setText("Peso");

        jT_usuario.setEnabled(false);

        buttonGroup1.add(jR_gerente);
        jR_gerente.setText("Gerente de Planta");
        jR_gerente.setEnabled(false);

        buttonGroup1.add(jR_sucursal);
        jR_sucursal.setText("Gerente de Sucursal");
        jR_sucursal.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel17.setText("Usuario");

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel18.setText("Contraseña");

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel19.setText("Ocupación");

        jLabel20.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel20.setText("Horario");

        jLabel21.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel21.setText("Tiempo Trabajando");

        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel22.setText("Sueldo");

        btn_GuardarPersonas.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btn_GuardarPersonas.setText("Guardar");
        btn_GuardarPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_GuardarPersonasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jT_identificacion1)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT_altura1)
                            .addComponent(jT_edad1)
                            .addComponent(jT_peso1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jC_sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jC_estadoC1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jC_TipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
            .addComponent(jSeparator1)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jT_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jT_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jR_gerente)
                        .addGap(18, 18, 18)
                        .addComponent(jR_sucursal)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jT_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(42, 42, 42)
                                .addComponent(jT_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_horario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_sueldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(132, 132, 132))))
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_GuardarPersonas)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jT_identificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jT_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jT_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jC_estadoC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jT_altura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jC_sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jT_peso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jC_TipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jR_sucursal)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jR_gerente)
                        .addComponent(jT_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jT_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jT_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jT_horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jT_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_GuardarPersonas)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTbl_principal.addTab("Agregar Personas", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102)));

        jC_ingresadoPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingresado Por:" }));

        jLabel23.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel23.setText("Título");

        btn_colorArt.setBackground(new java.awt.Color(153, 255, 153));
        btn_colorArt.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btn_colorArt.setText("Color");
        btn_colorArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_colorArtMouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel24.setText("Descripción");

        jT_descripcionArt.setColumns(20);
        jT_descripcionArt.setRows(5);
        jScrollPane1.setViewportView(jT_descripcionArt);

        jLabel25.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel25.setText("Editorial");

        buttonGroup2.add(rbtn_Comic);
        rbtn_Comic.setText("Comic");
        rbtn_Comic.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtn_ComicItemStateChanged(evt);
            }
        });

        buttonGroup2.add(rbtn_Figura);
        rbtn_Figura.setText("Figura");
        rbtn_Figura.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtn_FiguraItemStateChanged(evt);
            }
        });

        buttonGroup2.add(rbtn_Juego);
        rbtn_Juego.setText("Juego");
        rbtn_Juego.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtn_JuegoItemStateChanged(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel26.setText("Número de Volumen");

        jLabel27.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel27.setText("Artículo");

        jLabel28.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel28.setText("Descripción");

        jT_descripcionComic.setColumns(20);
        jT_descripcionComic.setRows(5);
        jScrollPane2.setViewportView(jT_descripcionComic);

        jLabel29.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel29.setText("Comic");

        jC_estadoComic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado:", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel30.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel30.setText("Estado del Comic");

        jLabel31.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel31.setText("Edición");

        jLabel32.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel32.setText("Casa de Elaboración");

        jLabel33.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel33.setText("País de Elaboración");

        jT_descripcionFigura.setColumns(20);
        jT_descripcionFigura.setRows(5);
        jScrollPane3.setViewportView(jT_descripcionFigura);

        jLabel34.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel34.setText("Descripción");

        jLabel35.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel35.setText("Figura");

        jT_instruccionesArm.setColumns(20);
        jT_instruccionesArm.setRows(5);
        jScrollPane4.setViewportView(jT_instruccionesArm);

        jLabel36.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel36.setText("Instrucciones");

        jLabel37.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel37.setText("Armado");

        jLabel38.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel38.setText("Tiempo de Garantía");

        btn_guardarArt.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btn_guardarArt.setText("Guardar");
        btn_guardarArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarArtMouseClicked(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel41.setText("Tamaño");

        jLabel42.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel42.setText("Puntuacion");

        jLabel43.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel43.setText("FIGURA");

        jLabel44.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel44.setText("JUEGO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator5)
            .addComponent(jSeparator6)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jT_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(18, 18, 18)
                                        .addComponent(jT_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jC_ingresadoPor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_colorArt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel27)
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addGap(45, 45, 45)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jT_nVol, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(jC_estadoComic, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel29))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addGap(18, 18, 18)
                                .addComponent(jT_Tam, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel42)
                                .addGap(18, 18, 18)
                                .addComponent(jT_puntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtn_Comic)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_Figura)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_Juego)))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jT_paisElab, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jT_casaElab, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(48, 48, 48)
                                .addComponent(jT_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel43))
                        .addGap(76, 76, 76))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel38)
                            .addGap(18, 18, 18)
                            .addComponent(jT_garantía, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btn_guardarArt))
                    .addComponent(jLabel44))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(402, Short.MAX_VALUE)
                    .addComponent(jLabel28)
                    .addGap(193, 193, 193)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_guardarArt)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(jT_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jC_ingresadoPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn_colorArt)
                                            .addComponent(jLabel25)
                                            .addComponent(jT_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel27)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(rbtn_Comic)
                                            .addComponent(rbtn_Figura)
                                            .addComponent(rbtn_Juego)
                                            .addComponent(jT_puntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel41)
                                        .addComponent(jT_Tam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(jT_nVol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jC_estadoComic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel30)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel29))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jT_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addComponent(jT_casaElab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jT_paisElab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel35))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel38)
                                    .addComponent(jT_garantía, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel44)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel37)))))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel28)
                    .addContainerGap(418, Short.MAX_VALUE)))
        );

        jTbl_principal.addTab("Agregar Artículo", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102)));

        jC_emisor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emisor" }));

        jLabel39.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel39.setText("Emisor");

        jLabel40.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel40.setText("Receptor");

        jC_receptor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Receptor" }));

        jT_enviarMensaje.setColumns(20);
        jT_enviarMensaje.setRows(5);
        jScrollPane5.setViewportView(jT_enviarMensaje);

        btn_enviar.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btn_enviar.setText("Enviar");
        btn_enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_enviarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addGap(18, 18, 18)
                        .addComponent(jC_emisor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel40)
                        .addGap(18, 18, 18)
                        .addComponent(jC_receptor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(btn_enviar)
                .addGap(36, 36, 36))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_enviar)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(jC_emisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40)
                            .addComponent(jC_receptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTbl_principal.addTab("Enviar Mensajes", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 102)));

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        jButton1.setText("Ver Historial");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emisor", "Receptor", "Mensaje"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );

        jTbl_principal.addTab("Historial de Mensajes", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTbl_principal)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTbl_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jC_TipoPersonaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jC_TipoPersonaItemStateChanged
        // TODO add your handling code here:

        if (jC_TipoPersona.getSelectedItem().toString().equalsIgnoreCase("Gerente")) {
            jT_usuario.setEnabled(true);
            jT_contraseña.setEnabled(true);
            jR_sucursal.setEnabled(true);
            jR_gerente.setEnabled(true);

            jT_ocupacion.setEnabled(false);
            jT_horario.setEnabled(false);
            jT_tiempo.setEnabled(false);
            jT_sueldo.setEnabled(false);
        } else if (jC_TipoPersona.getSelectedItem().toString().equalsIgnoreCase("Personal General")) {
            jT_ocupacion.setEnabled(true);
            jT_horario.setEnabled(true);
            jT_tiempo.setEnabled(true);
            jT_sueldo.setEnabled(true);

            jT_usuario.setEnabled(false);
            jT_contraseña.setEnabled(false);
            jR_sucursal.setEnabled(false);
            jR_gerente.setEnabled(false);
        } else {
            jT_ocupacion.setEnabled(false);
            jT_horario.setEnabled(false);
            jT_tiempo.setEnabled(false);
            jT_sueldo.setEnabled(false);

            jT_usuario.setEnabled(false);
            jT_contraseña.setEnabled(false);
            jR_sucursal.setEnabled(false);
            jR_gerente.setEnabled(false);
        }
    }//GEN-LAST:event_jC_TipoPersonaItemStateChanged

    private void btn_GuardarPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GuardarPersonasMouseClicked
        // TODO add your handling code here:
        String cargo = "";
        if (jR_gerente.isEnabled()) {
            cargo = "Gerente de Planta";
        } else if (jR_sucursal.isEnabled()) {
            cargo = "Sucursal de Planta";
        }
        boolean revision = true;
        switch (jC_TipoPersona.getSelectedIndex()) {
            case 0:
                JOptionPane.showMessageDialog(this, "Porfavor Llene todos los campos.");
                break;
            case 1:
                if (jT_usuario.getText().equals("")
                        || jT_contraseña.getText().equals("")
                        || cargo.equals("")
                        || jT_identificacion1.getText().equals("")
                        || jT_nombre1.getText().equals("")
                        || jT_edad1.getText().equals("")
                        || jC_sexo1.getSelectedItem().toString().equals("Seeccione")
                        || jC_estadoC1.getSelectedItem().toString().equals("Seleccione")
                        || jT_altura1.getText().equals("")
                        || jT_peso1.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Porfavor Llene todos los campos.");
                    revision = false;
                }
                break;
            case 2:
                if (jT_ocupacion.getText().equals("")
                        || jT_tiempo.getText().equals("")
                        || jT_horario.getText().equals("")
                        || jT_sueldo.getText().equals("")
                        || jT_identificacion1.getText().equals("")
                        || jT_nombre1.getText().equals("")
                        || jT_edad1.getText().equals("")
                        || jC_sexo1.getSelectedItem().toString().equals("")
                        || jC_estadoC1.getSelectedItem().toString().equals("")
                        || jT_altura1.getText().equals("")
                        || jT_peso1.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Porfavor Llene todos los campos.");
                    revision = false;
                }
                break;
            default:
                System.out.println("Hola");
        }//fin switch  
        if (revision == true) {
            boolean contraseña = false;
            String password = JOptionPane.showInputDialog("Ingrese la contraseña para guardar.");
            if (password.equals("clau123")) {
                contraseña = true;
            }
            if (contraseña == true) {
                try {
                    if (jC_TipoPersona.getSelectedIndex() == 1) {
                        personas.add(new Gerente(jT_usuario.getText(),
                                jT_contraseña.getText(),
                                cargo,
                                jT_identificacion1.getText(), jT_nombre1.getText(),
                                Integer.parseInt(jT_edad1.getText()),
                                jC_sexo1.getSelectedItem().toString(),
                                jC_estadoC1.getSelectedItem().toString(),
                                Double.parseDouble(jT_altura1.getText()),
                                Double.parseDouble(jT_peso1.getText())));
                        DefaultComboBoxModel modelRec = (DefaultComboBoxModel) jC_receptor.getModel();
                        modelRec.addElement(personas.get(personas.size() - 1));
                        jC_emisor.setModel(modelRec);//*/
                        DefaultComboBoxModel model = (DefaultComboBoxModel) jC_ingresadoPor.getModel();
                        model.addElement(personas.get(personas.size() - 1));
                        jC_ingresadoPor.setModel(model);
                        JOptionPane.showMessageDialog(this, "!Se ha agregado un Gerente!");
                        jT_usuario.setText("");
                        jT_contraseña.setText("");
                        cargo = "";
                        jT_identificacion1.setText("");
                        jT_nombre1.setText("");
                        jT_edad1.setText("");
                        jC_sexo1.getSelectedItem().toString();
                        jC_estadoC1.getSelectedItem().toString();
                        jT_altura1.setText("");
                        jT_peso1.setText("");
                    } else if (jC_TipoPersona.getSelectedIndex() == 2) {
                        personas.add(new PersonalGeneral(jT_ocupacion.getText(),
                                jT_tiempo.getText(),
                                jT_horario.getText(),
                                Double.parseDouble(jT_sueldo.getText()),
                                jT_identificacion1.getText(),
                                jT_nombre1.getText(),
                                Integer.parseInt(jT_edad1.getText()),
                                jC_sexo1.getSelectedItem().toString(),
                                jC_estadoC1.getSelectedItem().toString(),
                                Double.parseDouble(jT_altura1.getText()),
                                Double.parseDouble(jT_peso1.getText())));
                        JOptionPane.showMessageDialog(this, "!Se ha agregado una Persona General!");
                        DefaultComboBoxModel modelRec = (DefaultComboBoxModel) jC_receptor.getModel();
                        modelRec.addElement(personas.get(personas.size() - 1));
                        jC_emisor.setModel(modelRec);//*/
                        DefaultComboBoxModel model = (DefaultComboBoxModel) jC_ingresadoPor.getModel();
                        model.addElement(personas.get(personas.size() - 1));
                        jC_ingresadoPor.setModel(model);
                        jT_ocupacion.setText("");
                        jT_tiempo.setText("");
                        jT_horario.setText("");
                        jT_sueldo.setText("");
                        jT_identificacion1.setText("");
                        jT_nombre1.setText("");
                        jT_edad1.setText("");
                        jC_sexo1.getSelectedItem().toString();
                        jC_estadoC1.getSelectedItem().toString();
                        jT_altura1.setText("");
                        jT_peso1.setText("");
                    }//*/
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Porfavor ingrese dats válidos.");
                }
            }
        }
    }//GEN-LAST:event_btn_GuardarPersonasMouseClicked

    private void btn_guardarArtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarArtMouseClicked
        // TODO add your handling code here:

        boolean contraseña = false;
        String password = JOptionPane.showInputDialog("Ingrese la contraseña para guardar.");
        if (password.equals("clau123")) {
            contraseña = true;
        }
        if (contraseña == true) {
            if (rbtn_Comic.isEnabled()) {
                articulos.add(new Comic(
                        Integer.parseInt(jT_nVol.getText()),
                        jT_descripcionComic.getText(),
                        Integer.parseInt(jC_estadoComic.getSelectedItem().toString()),
                        jT_titulo.getText(),
                        btn_colorArt.getBackground(),
                        jT_descripcionArt.getText(),
                        jT_editorial.getText(),
                        Double.parseDouble(jT_Tam.getText()),
                        Double.parseDouble(jT_puntuacion.getText()),
                        personas.get(jC_ingresadoPor.getSelectedIndex())));
            } else if (rbtn_Figura.isEnabled()) {
                articulos.add(new Figura(jT_descripcionFigura.getText(),
                        jT_instruccionesArm.getText(),
                        jT_garantía.getText(),
                        jT_titulo.getText(),
                        btn_colorArt.getBackground(),
                        jT_descripcionArt.getText(),
                        jT_editorial.getText(),
                        Double.parseDouble(jT_Tam.getText()),
                        Double.parseDouble(jT_puntuacion.getText()),
                        personas.get(jC_ingresadoPor.getSelectedIndex())));
                JOptionPane.showMessageDialog(this, "!Se ha agregado un artículo!");
            } else if (rbtn_Juego.isEnabled()) {
                articulos.add(new Juego(Integer.parseInt(jT_edicion.getText()),
                        jT_casaElab.getText(),
                        jT_paisElab.getText(),
                        jT_titulo.getText(),
                        btn_colorArt.getBackground(),
                        jT_descripcionArt.getText(),
                        jT_editorial.getText(),
                        Double.parseDouble(jT_Tam.getText()),
                        Double.parseDouble(jT_puntuacion.getText()),
                        ((Persona) jC_ingresadoPor.getSelectedItem())));
                JOptionPane.showMessageDialog(this, "!Se ha agregado un artículo!");
            }
        }

    }//GEN-LAST:event_btn_guardarArtMouseClicked

    private void btn_colorArtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_colorArtMouseClicked
        // TODO add your handling code here:
        Color color = JColorChooser.showDialog(this, "Seleccione el color", Color.yellow);
        btn_colorArt.setBackground(color);
    }//GEN-LAST:event_btn_colorArtMouseClicked

    private void rbtn_ComicItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtn_ComicItemStateChanged
        // TODO add your handling code here:

        jT_nVol.setEnabled(true);
        jC_estadoComic.setEnabled(true);
        jT_descripcionComic.setEnabled(true);

        jT_descripcionFigura.setEnabled(false);
        jT_instruccionesArm.setEnabled(false);
        jT_garantía.setEnabled(false);

        jT_casaElab.setEnabled(false);
        jT_edicion.setEnabled(false);
        jT_paisElab.setEnabled(false);

    }//GEN-LAST:event_rbtn_ComicItemStateChanged

    private void rbtn_FiguraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtn_FiguraItemStateChanged
        // TODO add your handling code here:

        jT_casaElab.setEnabled(true);
        jT_edicion.setEnabled(true);
        jT_paisElab.setEnabled(true);

        jT_descripcionFigura.setEnabled(false);
        jT_instruccionesArm.setEnabled(false);
        jT_garantía.setEnabled(false);

        jT_nVol.setEnabled(false);
        jC_estadoComic.setEnabled(false);
        jT_descripcionComic.setEnabled(false);
    }//GEN-LAST:event_rbtn_FiguraItemStateChanged

    private void rbtn_JuegoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtn_JuegoItemStateChanged
        // TODO add your handling code here:

        jT_descripcionFigura.setEnabled(true);
        jT_instruccionesArm.setEnabled(true);
        jT_garantía.setEnabled(true);

        jT_nVol.setEnabled(false);
        jC_estadoComic.setEnabled(false);
        jT_descripcionComic.setEnabled(false);

        jT_casaElab.setEnabled(false);
        jT_edicion.setEnabled(false);
        jT_paisElab.setEnabled(false);
    }//GEN-LAST:event_rbtn_JuegoItemStateChanged

    private void btn_enviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_enviarMouseClicked
        // TODO add your handling code here:

        if (jT_enviarMensaje.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No se enviará ningun mensaje porque no existe tal mensaje :c");
        } else if (jC_emisor.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "No existe ningun emisor del mensaje");
        } else if (jC_receptor.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "No existe ningun receptor del mensaje");
        } else {
            JOptionPane.showMessageDialog(this, "!Mensaje enviado!");
        }

    }//GEN-LAST:event_btn_enviarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GuardarPersonas;
    private javax.swing.JButton btn_colorArt;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JButton btn_guardarArt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jC_TipoPersona;
    private javax.swing.JComboBox<String> jC_emisor;
    private javax.swing.JComboBox<String> jC_estadoC1;
    private javax.swing.JComboBox<String> jC_estadoComic;
    private javax.swing.JComboBox<String> jC_ingresadoPor;
    private javax.swing.JComboBox<String> jC_receptor;
    private javax.swing.JComboBox<String> jC_sexo1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jR_gerente;
    private javax.swing.JRadioButton jR_sucursal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jT_Tam;
    private javax.swing.JTextField jT_altura1;
    private javax.swing.JTextField jT_casaElab;
    private javax.swing.JPasswordField jT_contraseña;
    private javax.swing.JTextArea jT_descripcionArt;
    private javax.swing.JTextArea jT_descripcionComic;
    private javax.swing.JTextArea jT_descripcionFigura;
    private javax.swing.JTextField jT_edad1;
    private javax.swing.JTextField jT_edicion;
    private javax.swing.JTextField jT_editorial;
    private javax.swing.JTextArea jT_enviarMensaje;
    private javax.swing.JTextField jT_garantía;
    private javax.swing.JTextField jT_horario;
    private javax.swing.JTextField jT_identificacion1;
    private javax.swing.JTextArea jT_instruccionesArm;
    private javax.swing.JTextField jT_nVol;
    private javax.swing.JTextField jT_nombre1;
    private javax.swing.JTextField jT_ocupacion;
    private javax.swing.JTextField jT_paisElab;
    private javax.swing.JTextField jT_peso1;
    private javax.swing.JTextField jT_puntuacion;
    private javax.swing.JTextField jT_sueldo;
    private javax.swing.JTextField jT_tiempo;
    private javax.swing.JTextField jT_titulo;
    private javax.swing.JTextField jT_usuario;
    private javax.swing.JTable jTable1;
    private javax.swing.JTabbedPane jTbl_principal;
    private javax.swing.JRadioButton rbtn_Comic;
    private javax.swing.JRadioButton rbtn_Figura;
    private javax.swing.JRadioButton rbtn_Juego;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Persona> personas = new ArrayList();
    private ArrayList<String> mensajes = new ArrayList();
    private ArrayList<Articulo> articulos = new ArrayList();

}
