/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1_hectorreyes;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Onasis Reyes
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        jT_ocupacion.setEnabled(false);
        jT_horario.setEnabled(false);
        jT_tiempo.setEnabled(false);
        jT_sueldo.setEnabled(false);

        jT_usuario.setEnabled(!true);
        jT_contraseña.setEnabled(!true);
        jR_sucursal.setEnabled(!true);
        jR_gerente.setEnabled(!true);//*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jT_identificacion1 = new javax.swing.JTextField();
        jT_nombre1 = new javax.swing.JTextField();
        jT_edad1 = new javax.swing.JTextField();
        jT_altura1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jT_peso1 = new javax.swing.JTextField();
        jC_sexo1 = new javax.swing.JComboBox<>();
        jC_estadoC1 = new javax.swing.JComboBox<>();
        jC_TipoPersona = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jT_usuario = new javax.swing.JTextField();
        jT_contraseña = new javax.swing.JTextField();
        jR_gerente = new javax.swing.JRadioButton();
        jR_sucursal = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jT_sueldo = new javax.swing.JTextField();
        jT_ocupacion = new javax.swing.JTextField();
        jT_horario = new javax.swing.JTextField();
        jT_tiempo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btn_GuardarPersonas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102)));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel9.setText("Identificación");

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel15.setText("Altura");

        jC_sexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Hombre", "Mujer" }));

        jC_estadoC1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Casad@", "Solter@" }));

        jC_TipoPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Gerente", "Personal General" }));
        jC_TipoPersona.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jC_TipoPersonaItemStateChanged(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel16.setText("Tipo de Persona");

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel10.setText("Sexo");

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel11.setText("Nombre");

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel12.setText("Edad");

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel13.setText("Estado Civil");

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel14.setText("Peso");

        jT_usuario.setEnabled(false);

        jT_contraseña.setEnabled(false);

        jR_gerente.setText("Gerente de Planta");
        jR_gerente.setEnabled(false);

        jR_sucursal.setText("Gerente de Sucursal");
        jR_sucursal.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel17.setText("Usuario");

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel18.setText("Contraseña");

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel19.setText("Ocupación");

        jLabel20.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel20.setText("Horario");

        jLabel21.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel21.setText("Tiempo Trabajando");

        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel22.setText("Sueldo");

        btn_GuardarPersonas.setText("Guardar");
        btn_GuardarPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_GuardarPersonasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jT_identificacion1)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT_altura1)
                            .addComponent(jT_edad1)
                            .addComponent(jT_peso1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jC_sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jC_estadoC1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jC_TipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
            .addComponent(jSeparator1)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jT_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addGap(13, 13, 13)
                        .addComponent(jT_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jR_gerente)
                        .addGap(18, 18, 18)
                        .addComponent(jR_sucursal)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jT_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(42, 42, 42)
                                .addComponent(jT_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_horario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_sueldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(132, 132, 132))))
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_GuardarPersonas)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jT_identificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jT_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jT_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jC_estadoC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jT_altura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jC_sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jT_peso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jC_TipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jR_sucursal)
                        .addComponent(jLabel18)
                        .addComponent(jT_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jR_gerente))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jT_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jT_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jT_horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jT_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_GuardarPersonas)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Personas", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jC_TipoPersonaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jC_TipoPersonaItemStateChanged
        // TODO add your handling code here:

        if (jC_TipoPersona.getSelectedItem().toString().equalsIgnoreCase("Gerente")) {
            jT_usuario.setEnabled(true);
            jT_contraseña.setEnabled(true);
            jR_sucursal.setEnabled(true);
            jR_gerente.setEnabled(true);

            jT_ocupacion.setEnabled(false);
            jT_horario.setEnabled(false);
            jT_tiempo.setEnabled(false);
            jT_sueldo.setEnabled(false);
        } else if (jC_TipoPersona.getSelectedItem().toString().equalsIgnoreCase("Personal General")) {
            jT_ocupacion.setEnabled(true);
            jT_horario.setEnabled(true);
            jT_tiempo.setEnabled(true);
            jT_sueldo.setEnabled(true);

            jT_usuario.setEnabled(false);
            jT_contraseña.setEnabled(false);
            jR_sucursal.setEnabled(false);
            jR_gerente.setEnabled(false);
        } else {
            jT_ocupacion.setEnabled(false);
            jT_horario.setEnabled(false);
            jT_tiempo.setEnabled(false);
            jT_sueldo.setEnabled(false);

            jT_usuario.setEnabled(false);
            jT_contraseña.setEnabled(false);
            jR_sucursal.setEnabled(false);
            jR_gerente.setEnabled(false);
        }
    }//GEN-LAST:event_jC_TipoPersonaItemStateChanged

    private void btn_GuardarPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GuardarPersonasMouseClicked
        // TODO add your handling code here:
        String cargo = "";
        if (jR_gerente.isEnabled()) {
            cargo = "Gerente de Planta";
        } else if (jR_sucursal.isEnabled()) {
            cargo = "Sucursal de Sucursal";
        }
        
        
        
        boolean contraseña = false;
        if (JOptionPane.showInputDialog("Ingrese la contraseña para guardar.").equals("clau123")) {
            contraseña = true;
        }
        if (contraseña == true) {
            try {
                if (jC_TipoPersona.getSelectedIndex() == 1) {
                    personas.add(new Gerente(jT_usuario.getText(),
                            jT_contraseña.getText(),
                            cargo,
                            jT_identificacion1.getText(), jT_nombre1.getText(),
                            Integer.parseInt(jT_edad1.getText()),
                            jC_sexo1.getSelectedItem().toString(),
                            jC_estadoC1.getSelectedItem().toString(),
                            Double.parseDouble(jT_altura1.getText()),
                            Double.parseDouble(jT_peso1.getText())));
                    /* DefaultComboBoxModel model = (DefaultComboBoxModel) jC_receptor.getModel();
            model.addElement(personas.get(personas.size() - 1));
            jC_emisor.setModel(model);//*/
                    JOptionPane.showMessageDialog(this, "!Se ha agregado un Gerente!");
                } else if (jC_TipoPersona.getSelectedIndex() == 2) {
                    personas.add(new PersonalGeneral(jT_ocupacion.getText(),
                            jT_tiempo.getText(),
                            jT_horario.getText(),
                            Double.parseDouble(jT_sueldo.getText()),
                            jT_identificacion1.getText(),
                            jT_nombre1.getText(),
                            Integer.parseInt(jT_edad1.getText()),
                            jC_sexo1.getSelectedItem().toString(),
                            jC_estadoC1.getSelectedItem().toString(),
                            Double.parseDouble(jT_altura1.getText()),
                            Double.parseDouble(jT_peso1.getText())));
                    /*DefaultComboBoxModel model = (DefaultComboBoxModel) jC_receptor.getModel();
        model.addElement(personas.get(personas.size() - 1));
        jC_emisor.setModel(model);//*/
                    JOptionPane.showMessageDialog(this, "!Se ha agregado una Persona General!");
                }//*/
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Porfavor ingrese dats válidos.");
            }
        }
    }//GEN-LAST:event_btn_GuardarPersonasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GuardarPersonas;
    private javax.swing.JComboBox<String> jC_TipoPersona;
    private javax.swing.JComboBox<String> jC_estadoC1;
    private javax.swing.JComboBox<String> jC_sexo1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jR_gerente;
    private javax.swing.JRadioButton jR_sucursal;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jT_altura1;
    private javax.swing.JTextField jT_contraseña;
    private javax.swing.JTextField jT_edad1;
    private javax.swing.JTextField jT_horario;
    private javax.swing.JTextField jT_identificacion1;
    private javax.swing.JTextField jT_nombre1;
    private javax.swing.JTextField jT_ocupacion;
    private javax.swing.JTextField jT_peso1;
    private javax.swing.JTextField jT_sueldo;
    private javax.swing.JTextField jT_tiempo;
    private javax.swing.JTextField jT_usuario;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Persona> personas = new ArrayList();

}
